### ISSUE TITLE
ECIES encryption/decryption code is not correct

### ISSUE THREAD

**Issue by jonbonazza** [pki-io/pki.io#37]
While the encryption works as far as the tests are concerned, the key derivation function is broken. It returns an array of 32 0's, which is obviously incorrect. What this means is, regardless of public or private key, the AES key will always be 16 0's. Not exactly secure. :P I tried switching it to use the existing ExpandKey() function (which I didn't even realize we had), but some other issues creep up when using that. I need to revisit the ECIES encryption/decryption code in its entirety. I will add any documentation I use in the process to the comments.

**Comment by zeroXten** [comment]
Yeah, we need to be very clear about what any crypto code is doing. Also, this is exactly the sort of thing we should have security-focused unit tests written for. For example, we could run key generation code through a chi-square test and length tests to make sure it isn't completely broken.

**Comment by zeroXten** [comment]
Also a good case for code coverage.. you don't want that 5% not covered to have core crypto in it :D

**Comment by jonbonazza** [comment]
Yep.  PR #39 fixes this issue and the coverage of the crypto module is now 82%.the only cases left to test are the error conditions. :+1
